### ISSUE TITLE
For companies of Btech/Mtech of All_Branches branch_map needs to be updated in company.views.py

### ISSUE THREAD

**Issue by bluenovice** [aakashrana1995/svnit-tnp#4]
Whenever any company tries to register for Btceh/Mtech of __all Branches__ a _keyerror_ is thrown.
The branch_mapper which is created in company.views.py needs to be updated for such a company too

Let me give you the correct format.
Current code
```
def create_branch_map():
    branch_map = {}
    branch_map['CO'] = 'Computer Engineering'
    branch_map['ME'] = 'Mechanical Engineering'
    branch_map['CE'] = 'Civil Engineering'
    branch_map['EE'] = 'Electrical Engineering'
    branch_map['CH'] = 'Chemical Engineering'
    branch_map['EC'] = 'Electronics Engineering'
    branch_map['PHY'] = 'Physics'
    branch_map['CHEM'] = 'Chemistry'
    branch_map['MATH'] = 'Mathematics'

    return branch_map
```

needs to be  changed to .
```
    branch_map = {}
    branch_map['CO'] = 'Computer Engineering'
    branch_map['ME'] = 'Mechanical Engineering'
    branch_map['CE'] = 'Civil Engineering'
    branch_map['EE'] = 'Electrical Engineering'
    branch_map['CH'] = 'Chemical Engineering'
    branch_map['EC'] = 'Electronics Engineering'
    branch_map['PHY'] = 'Physics'
    branch_map['CHEM'] = 'Chemistry'
    branch_map['MATH'] = 'Mathematics'
#below line needs to be added.
    branch_map['ALL'] = 'all branches'
#above line needs to be added
    return branch_map
```

**Comment by aakashrana1995** [comment]
Let's process 'All Branches' differently.

**Here's the approach:**
Whenever a company is added with 'Eligible Branches' (EB) as 'All Branches', we will handle the backend code such that EB will store all branches found in the Branch model (_CO, CH, ME, PHY, etc_) instead of just one field 'ALL'.

The benefits of this are many:
_E.g._ When you open the home page where you see a list of jobs, the queryset filters the jobs according to your branch. If we would have just stored 'ALL', we would also have to put a special check to filter jobs according to your branch as well as jobs for which 'All Branches' are eligible. So, whenever any filter/check is to be made in any part of code related to branches, the case of 'All Branches' will have to be considered separately everywhere.

Instead, during job entry creation only we will handle all branches as told above.

**Comment by aakashrana1995** [comment]
```
job = job_form.save(commit=False)
job.company = company
job.save()
job_form.save_m2m()
```

After the above code is executed in 'company/views.py', our Job is saved.
We can add these lines after that to handle the proposed approach:
Variable `job` contains our current Job object.

```
all_branches = Branch.objects.exclude(name='ALL')
eb = job.eligible_branches.values_list('name',flat=True)
if ('ALL' in eb):
    for brnch in all_branches:
        job.eligible_branches.add(brnch)
```

I think this should work. Alternatively, we could also look into post_save signals as given in this documentation. [Signals](https://docs.djangoproject.com/en/1.10/topics/signals/), but I think signals would become an overkill for this small thing.

**Comment by aakashrana1995** [comment]
Modified code

```
eb = job.eligible_branches.filter(name='ALL')
for all_type_branch in eb:
    all_branches = Branch.objects.filter(degree=all_type_branch.degree).exclude(name='ALL')
    for branch in all_branches:
        job.eligible_branches.add(branch)
```

This will handle fields like 'BTech, All Branches', 'MTech, All Branches' by inserting all branches for that degree respectively.

**Comment by aakashrana1995** [comment]
Final code :grin: 

```
eb = job.eligible_branches.filter(name='ALL')
for all_type_branch in eb:
    all_branches = Branch.objects.filter(degree=all_type_branch.degree).exclude(name='ALL')
    for branch in all_branches:
        job.eligible_branches.add(branch)
        job.eligible_branches.remove(all_type_branch)
```
